-- Migration: 004_signals
-- Description: Trading signals generated by signal engines
-- Created: 2026-01-30

-- Signal types enum
CREATE TYPE signal_type AS ENUM (
    'price_movement',
    'volatility_spike', 
    'gap_up',
    'gap_down',
    'volume_surge',
    'breakout',
    'breakdown',
    'custom'
);

-- Signal direction enum
CREATE TYPE signal_direction AS ENUM (
    'bullish',
    'bearish',
    'neutral'
);

CREATE TABLE IF NOT EXISTS signals (
    id BIGSERIAL PRIMARY KEY,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id) ON DELETE CASCADE,
    signal_date DATE NOT NULL,
    signal_type signal_type NOT NULL,
    signal_direction signal_direction DEFAULT 'neutral',
    signal_strength DECIMAL(5, 2),
    value DECIMAL(12, 4),
    threshold DECIMAL(12, 4),
    description TEXT,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT uq_signals_instrument_date_type UNIQUE (instrument_id, signal_date, signal_type)
);

-- Indexes for signal queries
CREATE INDEX IF NOT EXISTS idx_signals_instrument_id ON signals(instrument_id);
CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_signals_type_date ON signals(signal_type, signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_signals_instrument_date ON signals(instrument_id, signal_date DESC);

-- Index for finding strong signals
CREATE INDEX IF NOT EXISTS idx_signals_strength 
    ON signals(signal_date DESC, signal_strength DESC) 
    WHERE signal_strength IS NOT NULL;

COMMENT ON TABLE signals IS 'Trading signals generated by various signal engines';
COMMENT ON COLUMN signals.signal_strength IS 'Signal strength score (0-100)';
COMMENT ON COLUMN signals.value IS 'The calculated value that triggered the signal';
COMMENT ON COLUMN signals.threshold IS 'The threshold value that was exceeded';
